force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>A class or activity for which participants are registered and session attendances are taken</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Attendance__c/Program_Attendance__c.object-meta.xml
<CustomObject>
    <description>Contact who attends a specific Session of a Program. 
Junction object connecting Contact with Session.</description>
    <label>Program Attendance</label>
    <nameField>
        <displayFormat>Attendance-{0000}</displayFormat>
        <label>Attendance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Referenced by Apex logic in TakeAttendance and ManageRegistrations. Auto-populated by Apex or Process Builder.</description>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/Program_Session__c.field-meta.xml
<CustomField>
    <fullName>Program_Session__c</fullName>
    <label>Program Session</label>
    <referenceTo>Program_Session__c</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/ServiceDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceDate__c</fullName>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Registration__c/Program_Registration__c.object-meta.xml
<CustomObject>
    <description>Junction object connecting Programs with Contacts</description>
    <label>Program Registration</label>
    <nameField>
        <displayFormat>Registration-{0000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Person signed up for the program</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Registrations</relationshipLabel>
    <relationshipName>Program_Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Registration__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program which contact is signed up for</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Registrations</relationshipLabel>
    <relationshipName>Program_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Session__c/Program_Session__c.object-meta.xml
<CustomObject>
    <description>Junction object connecting Program with Attendee</description>
    <label>Program Session</label>
    <nameField>
        <displayFormat>Session-{0000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Session meeting date</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Session__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Sessions </relationshipLabel>
    <relationshipName>Program_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestAttendanceFactory.cls
//Generates test data to use in test classes
//ManageRegistrationsControllerTest, TakeAttendanceControllerTest
@isTest
public class TestAttendanceFactory {
    public static Program__c createContactsWithAttendances(){
        List<Contact> conList = new List<Contact>{
            new Contact(FirstName='Client',LastName='Notcurrent'),
                new Contact(FirstName='Client',LastName='Current'),
                new Contact(FirstName='Client',LastName='New'),
                new Contact(FirstName='Client',LastName='Noshow')};    
                    insert conList;	
        
        Program__c wineClass = new Program__c(Name='Wine Tasting');
        insert wineClass;
        
        List<Program_Registration__c> regList = new List<Program_Registration__c>();
        for(Contact c : conList){
            Program_Registration__c r = new Program_Registration__c(Contact__c=c.id, Program__c=wineClass.Id);
            regList.add(r);
        }
        
        insert regList;
        
        List<Program_Session__c> classList = new List<Program_Session__c>();
        for(Integer i=0; i<6; i++){
            Program_Session__c sd = new Program_Session__c(Date__c=Date.today().addDays(-(i*10+5)), Program__c=wineClass.Id);
            classList.add(sd);
        } 
        
        insert classList;
        
        
        //Contacts with no attendance in last 30 days will have Registration deleted
        
        //Contact 'Client Notcurrent' has no attendance within 30 days and Registration WILL be deleted
        //Contact 'Client Current' has one attendance within 30 days and Registration will not be deleted
        //Contact 'Client New' has all attendance within 30 days and Registration will not be deleted
        //Contact 'Client Noshow' has no attendances at all but Registration is recent and will not be deleted
        
        
        
        List<Program_Attendance__c> attList = new List<Program_Attendance__c>{
            new Program_Attendance__c(Contact__c=conList[0].Id, Program_Session__c=classList[5].Id, ServiceDate__c=classList[5].Date__c, Program__c=wineclass.Id),
                new Program_Attendance__c(Contact__c=conList[0].Id, Program_Session__c=classList[4].Id, ServiceDate__c=classList[4].Date__c, Program__c=wineclass.Id),
                new Program_Attendance__c(Contact__c=conList[0].Id, Program_Session__c=classList[3].Id, ServiceDate__c=classList[3].Date__c, Program__c=wineclass.Id),
                new Program_Attendance__c(Contact__c=conList[1].Id, Program_Session__c=classList[4].Id, ServiceDate__c=classList[4].Date__c, Program__c=wineclass.Id),
                new Program_Attendance__c(Contact__c=conList[1].Id, Program_Session__c=classList[2].Id, ServiceDate__c=classList[2].Date__c, Program__c=wineclass.Id),
                new Program_Attendance__c(Contact__c=conList[1].Id, Program_Session__c=classList[1].Id, ServiceDate__c=classList[1].Date__c, Program__c=wineclass.Id),
                new Program_Attendance__c(Contact__c=conList[2].Id, Program_Session__c=classList[2].Id, ServiceDate__c=classList[2].Date__c, Program__c=wineclass.Id),
                new Program_Attendance__c(Contact__c=conList[2].Id, Program_Session__c=classList[1].Id, ServiceDate__c=classList[1].Date__c, Program__c=wineclass.Id),
                new Program_Attendance__c(Contact__c=conList[2].Id, Program_Session__c=classList[0].Id, ServiceDate__c=classList[0].Date__c, Program__c=wineclass.Id)};
                    
        try {
        		insert attList; 
        	} catch(DmlException e) {
            	System.debug('Insert failed: ' + e);
        }
              
        return wineClass;
    }	
    
}