force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>A class or activity for which participants are registered and session attendances are taken</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Attendance__c/Program_Attendance__c.object-meta.xml
<CustomObject>
    <description>Contact who attends a specific Session of a Program. 
Junction object connecting Contact with Session.</description>
    <label>Program Attendance</label>
    <nameField>
        <displayFormat>Attendance-{0000}</displayFormat>
        <label>Attendance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Referenced by Apex logic in TakeAttendance and ManageRegistrations. Auto-populated by Apex or Process Builder.</description>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/Program_Session__c.field-meta.xml
<CustomField>
    <fullName>Program_Session__c</fullName>
    <label>Program Session</label>
    <referenceTo>Program_Session__c</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/ServiceDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceDate__c</fullName>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Registration__c/Program_Registration__c.object-meta.xml
<CustomObject>
    <description>Junction object connecting Programs with Contacts</description>
    <label>Program Registration</label>
    <nameField>
        <displayFormat>Registration-{0000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Person signed up for the program</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Registrations</relationshipLabel>
    <relationshipName>Program_Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Registration__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program which contact is signed up for</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Registrations</relationshipLabel>
    <relationshipName>Program_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Session__c/Program_Session__c.object-meta.xml
<CustomObject>
    <description>Junction object connecting Program with Attendee</description>
    <label>Program Session</label>
    <nameField>
        <displayFormat>Session-{0000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Session meeting date</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Session__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Sessions </relationshipLabel>
    <relationshipName>Program_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TakeAttendanceControllerTest.cls
@isTest
public class TakeAttendanceControllerTest {

    @isTest static void TestGetRegistrations() {
        
        Program__c wineClass = makeClass();
        List<Contact> conList = makeContacts();
        List<Program_Registration__c> regList = makeRegistrations(conList, wineClass);
        Test.startTest();
        List<Program_Registration__c> regsFound = TakeAttendanceController.getRegistrations(wineClass.Id);
        System.AssertEquals(5, regsFound.size());
        Test.stopTest();
    }   
    
    @isTest static void TestGetAttendances() {
        
        Program__c wineClass = makeClass();
        List<Contact> conList = makeContacts();
        List<Program_Registration__c> regList = makeRegistrations(conList, wineClass);
        Program_Session__c testSession = makeSession(wineClass);
        List<Program_Attendance__c> attList = makeAttendance(conList, wineClass, regList, testSession);
        Test.startTest();
        List<Program_Attendance__c> attsFound = TakeAttendanceController.getAttendances(wineClass.Id, testSession.id);
        System.AssertEquals(5, attsFound.size());
        Test.stopTest();
    }  
    
    @isTest static void TestGetProgramSession() {
        Program__c wineClass = makeClass();
        Program_Session__c testSession = makeSession(wineClass);
        Program_Session__c result = TakeAttendanceController.getProgramSession(testSession.id);
        Test.startTest();
        System.assertEquals(date.today(), result.Date__c);
        System.assertEquals(wineClass.id, result.Program__c);
        Test.stopTest();
    }
    
    @isTest static void TestGetAttendanceContacts() {
        Program__c wineClass = makeClass();
        List<Contact> conList = makeContacts();
        List<Program_Registration__c> regList = makeRegistrations(conList, wineClass);
        Program_Session__c testSession = makeSession(wineClass);
        List<Program_Attendance__c> attList = makeAttendance(conList, wineClass, regList, testSession);
        Test.startTest();
        List<Id> result = TakeAttendanceController.getAttendanceContacts(attList);
        System.AssertEquals(conList[4].Id, result[4]);
        Test.stopTest();        
    }
    
    @isTest static void TestGetRegistrationContacts() {
        Program__c wineClass = makeClass();
        List<Contact> conList = makeContacts();
        List<Program_Registration__c> regList = makeRegistrations(conList, wineClass);
        Program_Session__c testSession = makeSession(wineClass);
        List<Program_Attendance__c> attList = makeAttendance(conList, wineClass, regList, testSession);
        Test.startTest();
        List<Id> result = TakeAttendanceController.getRegistrationContacts(regList);
        System.AssertEquals(conList[4].Id, result[4]);
        Test.stopTest();        
    }
       
    
    @isTest static void TestGetSessionAttendanceForEdit() {
        Program__c wineClass = makeClass();
        List<Contact> conList = makeContacts();
        List<Program_Registration__c> regList = makeRegistrations(conList, wineClass);
        List<String> regIds = new List<String>();
        for (Integer i = 0; i<3; i++) {
            regIds.add(regList[i].Id);
        }
        Program_Session__c session = new Program_Session__c(Program__c=wineClass.Id, Date__c=date.newInstance(2017,12,31));
        insert session;
        
        // save these registrations
        TakeAttendanceController.saveAttendances(wineClass.Id, regIds, session);
        test.startTest();
        List<TakeAttendanceController.AttendanceFormWrapper> result = TakeAttendanceController.getSessionAttendanceForEdit(session.Id);
        List<Boolean> checked = new List<Boolean>();
        for(TakeAttendanceController.AttendanceFormWrapper r : result) {
            checked.add(r.CheckboxSetting);
        }
        System.AssertEquals(true, checked[0]);  
        System.AssertEquals(true, checked[1]);
        System.AssertEquals(true, checked[2]);
        System.AssertEquals(false, checked[3]);
        System.AssertEquals(false, checked[4]);                  
        test.stopTest();
    }
    
    @isTest static void TestSaveAttendances() {

        Program__c wineClass = makeClass();
        List<Contact> conList = makeContacts();
        List<Program_Registration__c> regList = makeRegistrations(conList, wineClass);
        List<String> regIds = new List<String>();
        for(Program_Registration__c r: regList) {
            regIds.add(r.Id);
        }
        Program_Session__c testSession = makeSession(wineClass);
        Test.startTest(); 
        TakeAttendanceController.saveAttendances(wineClass.Id, regIds, testSession);
        List<Program_Attendance__c> result = [SELECT Contact__c FROM Program_Attendance__c];
        System.assertEquals(conList[4].Id, result[4].Contact__c);
        Test.stopTest();
    }
    
    @isTest static void testSaveEditedAttendanceEdit() {
        Program__c wineClass = makeClass();
        List<Contact> conList = makeContacts();
        List<Program_Registration__c> regList = makeRegistrations(conList, wineClass);
        List<String> regIds = new List<String>();
        for (Integer i = 0; i<3; i++) {
            regIds.add(regList[i].Id);
        }
        Program_Session__c session = new Program_Session__c(Program__c=wineClass.Id, Date__c=date.newInstance(2017,12,31));
        insert session;
        
        // save these registrations
         TakeAttendanceController.saveAttendances(wineClass.Id, regIds, session);
        // then make a new list: 0 and 1 will be deleted, 2 remains, 3 and 4 will be added
        regIds = new List<String>();
        for (Integer i = 2; i<5; i++) {
            regIds.add(regList[i].Id);
        }
        
        Test.startTest();      
        TakeAttendanceController.saveEditedAttendance(session.id, regIds);
        List<TakeAttendanceController.AttendanceFormWrapper> checkBoxes = TakeAttendanceController.getSessionAttendanceForEdit(session.id);
        List<Boolean> checked = new List<Boolean>();
        for (Integer i=0; i<5; i++) {
            checked.add(checkBoxes[i].CheckboxSetting);
        }
        System.debug(checked);
        
        System.AssertEquals(false, checked[0]);  
        System.AssertEquals(false, checked[1]);
        System.AssertEquals(true, checked[2]);
        System.AssertEquals(true, checked[3]);
        System.AssertEquals(true, checked[4]);
        
        Test.stopTest();
    }
    
    
    //Data creation methods -----------------------------------------------------------------
    
    static List<Contact> makeContacts() {
        List<Contact> conList = new List<Contact>();
        for(Integer i=0; i<5; i++) {
            Contact con = new Contact(FirstName='Class',LastName='Participant'+i);
            conList.add(con);
        }   
        insert conList;	
        return conList;
    }
    
    static Program__c makeClass() {
        Program__c wineClass = new Program__c(Name='Wine Tasting');
        insert wineClass;
        return wineClass;
    }
    
    static List<Program_Registration__c> makeRegistrations(List<Contact> conList, Program__c wineClass) {
        List<Program_Registration__c> regList = new List<Program_Registration__c>();
        for(Contact c : conList){
            Program_Registration__c r = new Program_Registration__c(Contact__c=c.id, Program__c=wineClass.Id);
            regList.add(r);
        }
        
        insert regList;
        return regList;
    }
    
    static Program_Session__c makeSession(Program__c wineClass) {
        Program_Session__c testSession = new Program_Session__c();
        testSession.Date__c = date.today();
        testSession.Program__c = wineClass.id;
        insert testSession;
        return testSession;
       
    }
    
    static List<Program_Attendance__c> makeAttendance(List<Contact> conList, Program__c wineClass, List<Program_Registration__c> regList, Program_Session__c testSession) {
        List<Program_Attendance__c> attList = new List<Program_Attendance__c>();
        for(Program_Registration__c reg: regList) {
            Program_Attendance__c att = new Program_Attendance__c();
            att.Program_Session__c = testSession.Id;
            att.Program__c = wineClass.Id;
            att.Contact__c = reg.Contact__c;
            att.ServiceDate__c = testSession.Date__c;
            attList.add(att);
        }
 
    insert attList;  
    return attList;
    }
    
}