force-app/main/default/objects/Contact/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <description>Enter bar code by placing mouse in this field and then scanning a bar code.  Used to record attendance by scanning on the program session page.</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter bar code by placing mouse in this field and then scanning a bar code.  Used to record attendance by scanning on the program session page.</inlineHelpText>
    <label>Barcode</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>A class or activity for which participants are registered and session attendances are taken</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Attendance__c/Program_Attendance__c.object-meta.xml
<CustomObject>
    <description>Contact who attends a specific Session of a Program. 
Junction object connecting Contact with Session.</description>
    <label>Program Attendance</label>
    <nameField>
        <displayFormat>Attendance-{0000}</displayFormat>
        <label>Attendance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Attendance__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Referenced by Apex logic in TakeAttendance and ManageRegistrations. Auto-populated by Apex or Process Builder.</description>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/Program_Session__c.field-meta.xml
<CustomField>
    <fullName>Program_Session__c</fullName>
    <label>Program Session</label>
    <referenceTo>Program_Session__c</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Session__c/Program_Session__c.object-meta.xml
<CustomObject>
    <description>Junction object connecting Program with Attendee</description>
    <label>Program Session</label>
    <nameField>
        <displayFormat>Session-{0000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Session meeting date</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Session__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Sessions </relationshipLabel>
    <relationshipName>Program_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ScanAttendanceControllerTest.cls
@isTest
public class ScanAttendanceControllerTest {
    
    @isTest static void testGetContacts() {
        makeData();
        test.startTest();
        Contact con = ScanAttendanceController.getContacts('123456');
        System.assertEquals('Barcode', con.LastName);
        con = ScanAttendanceController.getContacts('');
        System.assertEquals(null, con);
        test.stopTest();
    }
    
    @isTest static void testSaveAttendance() {
        makeData();
        Id psid = [SELECT Id FROM Program_Session__c LIMIT 1].Id;
        test.startTest();
        Contact con = ScanAttendanceController.getContacts('123456');
        ScanAttendanceController.saveAttendance(con, psid);
        List<Program_Attendance__c> result = [SELECT Id FROM Program_Attendance__c];
        System.assertEquals(1, result.size());
        test.stopTest();        
    }
       
       
    @isTest static void testAccess() {
        Id p = [SELECT Id FROM profile WHERE name = 'Standard User'].Id;
        User u = new User(
            Alias = 'testu',
            Email = 'test@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZonesidKey = 'America/Los_Angeles',
            ProfileId = p,
            UserName = 'test@SGexample.com',
            IsActive = true);
        insert u;
        
        system.runAs(u) {
            
            try {
                ScanAttendanceController.checkContactReadAccess();
            } catch(Exception e) {
                System.assert(e.getTypeName().contains('System.NoAccessException'));
            }
            
            try {
                ScanAttendanceController.checkContactFieldReadAccess();
            } catch(Exception e) {
                System.assert(e.getTypeName().contains('System.NoAccessException'));
            }
            
            try {
                ScanAttendanceController.checkProgramReadAccess();
            } catch(Exception e) {
                System.assert(e.getTypeName().contains('System.NoAccessException'));
            }
            
            try {
                ScanAttendanceController.checkProgramFieldReadAccess();
            } catch(Exception e) {
                System.assert(e.getTypeName().contains('System.NoAccessException'));
            }
            
            try {
                ScanAttendanceController.checkProgramSessionReadAccess();
            } catch(Exception e) {
                System.assert(e.getTypeName().contains('System.NoAccessException'));
            }
            
            try {
                ScanAttendanceController.checkProgramSessionFieldReadAccess();
            } catch(Exception e) {
                System.assert(e.getTypeName().contains('System.NoAccessException'));
            }
            
            try {
                ScanAttendanceController.checkAttendanceCreateAccess();
            } catch(Exception e) {
                System.assert(e.getTypeName().contains('System.NoAccessException'));
            }
            
            try {
                ScanAttendanceController.checkAttendanceFieldUpdateAccess();
            } catch(Exception e) {
                System.assert(e.getTypeName().contains('System.NoAccessException'));
            }
            
        }
    }
    
    public static void makeData() {
        
        Program__c prog = new Program__c(Name='Welcome');
        insert prog;
        Program_Session__c ps = new Program_Session__c(Date__c = date.today(), Program__c = prog.id);
        insert ps;
        Contact con1 = new Contact(FirstName='test', LastName='NoBarcode',Barcode__c = '');
        insert con1;
        Contact con2 = new Contact(FirstName='test', LastName='Barcode',Barcode__c = '123456');
        insert con2;
        
    }    
}