force-app/main/default/objects/Contact/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <description>Enter bar code by placing mouse in this field and then scanning a bar code.  Used to record attendance by scanning on the program session page.</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter bar code by placing mouse in this field and then scanning a bar code.  Used to record attendance by scanning on the program session page.</inlineHelpText>
    <label>Barcode</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/YearOfBirth__c.field-meta.xml
<CustomField>
    <fullName>YearOfBirth__c</fullName>
    <formula>TEXT(YEAR( Birthdate))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year Of Birth</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>A class or activity for which participants are registered and session attendances are taken</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Attendance__c/Program_Attendance__c.object-meta.xml
<CustomObject>
    <description>Contact who attends a specific Session of a Program. 
Junction object connecting Contact with Session.</description>
    <label>Program Attendance</label>
    <nameField>
        <displayFormat>Attendance-{0000}</displayFormat>
        <label>Attendance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Attendance__c/fields/Barcode_Scanned__c.field-meta.xml
<CustomField>
    <fullName>Barcode_Scanned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automatically checked by scanning process if attendance record created by scan.  Use in reporting to identify scanned attendance records.</description>
    <inlineHelpText>Automatically checked by scanning process if attendance record created by scan.  Use in reporting to identify scanned attendance records.</inlineHelpText>
    <label>Barcode Scanned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Referenced by Apex logic in TakeAttendance and ManageRegistrations. Auto-populated by Apex or Process Builder.</description>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/Program_Session__c.field-meta.xml
<CustomField>
    <fullName>Program_Session__c</fullName>
    <label>Program Session</label>
    <referenceTo>Program_Session__c</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/ServiceDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceDate__c</fullName>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Session__c/Program_Session__c.object-meta.xml
<CustomObject>
    <description>Junction object connecting Program with Attendee</description>
    <label>Program Session</label>
    <nameField>
        <displayFormat>Session-{0000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Session meeting date</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Session__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Sessions </relationshipLabel>
    <relationshipName>Program_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ScanAttendanceController.cls
public with sharing class ScanAttendanceController {

    @AuraEnabled
    public static Contact getContacts(String barcode) {
        if(barcode != null && barcode != '') {
            checkContactReadAccess();
            List<Contact> cons = new List<Contact>(); 
            cons = [SELECT FirstName, LastName, Birthdate, YearOfBirth__c, MailingPostalCode FROM Contact WHERE Barcode__c = :barcode LIMIT 1];
            System.debug(cons);
            return cons[0];
        } else {
            return null;
        }
    }
    
    @AuraEnabled
    public static void saveAttendance(Contact con, Id recordId) {
            
        checkProgramReadAccess();
        checkProgramSessionReadAccess();
        checkAttendanceCreateAccess();
             
        Program_Session__c ps = [SELECT Program__c, Date__c FROM Program_Session__c WHERE Id = :recordId];
             
        Program_Attendance__c pa = new Program_Attendance__c();
        pa.Contact__c = con.Id;
        pa.Program__c = ps.Program__c;
        pa.ServiceDate__c = ps.Date__c;
        pa.Program_Session__c = recordId;
        pa.Barcode_Scanned__c = true;
        insert pa; 
    }
    
    
    //****************************CRUD methods*****************************
    
    public static void checkContactReadAccess() {
        if (!Schema.sObjectType.Contact.isAccessible()) {
            throw new System.NoAccessException();
        }
        checkContactFieldReadAccess();
    }
    
    public static void checkContactFieldReadAccess() {
        
        String [] conAccessFields = new String []  {'FirstName', 'LastName', 'Birthdate', 'Barcode__c'};                                                        
        Map<String, Schema.SOBjectField> m = Schema.SOBjectType.Contact.fields.getMap();
        System.debug(m);
        for (String fieldToCheck : conAccessFields) {
            if (!m.get(fieldToCheck).getDescribe().isAccessible()) {
                System.debug('User cannot read Contact fields');
                throw new System.NoAccessException();
            }
        }
    }
    
    public static void checkProgramReadAccess() {
        if (!Schema.sObjectType.Program__c.isAccessible()) {
            throw new System.NoAccessException();
        }
        checkProgramFieldReadAccess();
    }
    
    public static void checkProgramFieldReadAccess() {
        
        String [] psAccessFields = new String []  {'Id','Name'};                                                
        Map<String, Schema.SOBjectField> m = Schema.SOBjectType.Program_Session__c.fields.getMap();
        for (String fieldToCheck : psAccessFields) {
            if (!m.get(fieldToCheck).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }
    }
    
    
    public static void checkProgramSessionReadAccess() {
        
        if (!Schema.sObjectType.Program_Session__c.isAccessible()) {
            throw new System.NoAccessException();
        }
        
        checkProgramSessionFieldReadAccess();
    }
        
	public static void checkProgramSessionFieldReadAccess() {
        
        String [] psAccessFields = new String []  {'Id','Program__c', 'Date__c'};                                                
        Map<String, Schema.SOBjectField> m = Schema.SOBjectType.Program_Session__c.fields.getMap();
        for (String fieldToCheck : psAccessFields) {
            if (!m.get(fieldToCheck).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }
    }
    
    public static void checkAttendanceCreateAccess() {      
        if (!Schema.sObjectType.Program_Attendance__c.isCreateable()) {
            throw new System.NoAccessException();   
        }
        checkAttendanceFieldUpdateAccess();
    }
    
    public static void checkAttendanceFieldUpdateAccess() {
        
        String [] attAccessFields = new String []  {'Program__c', 'ServiceDate__c', 'Barcode_Scanned__c'};                                                
        Map<String, Schema.SOBjectField> mm = Schema.SOBjectType.Program_Attendance__c.fields.getMap();
        for (String fieldToCheck : attAccessFields) {
            if (!mm.get(fieldToCheck).getDescribe().isUpdateable()) {
                System.debug('Not updateable' + fieldToCheck);
                throw new System.NoAccessException();
            }
        }
    }
    
    
}