force-app/main/default/objects/Contact/fields/Barcode__c.field-meta.xml
<CustomField>
    <fullName>Barcode__c</fullName>
    <description>Enter bar code by placing mouse in this field and then scanning a bar code.  Used to record attendance by scanning on the program session page.</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter bar code by placing mouse in this field and then scanning a bar code.  Used to record attendance by scanning on the program session page.</inlineHelpText>
    <label>Barcode</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>A class or activity for which participants are registered and session attendances are taken</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <description>Days on which sessions are held.</description>
    <inlineHelpText>Days on which sessions are held.</inlineHelpText>
    <label>Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Instructor1__c.field-meta.xml
<CustomField>
    <fullName>Instructor1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Program instructor must be entered as a contact.</description>
    <inlineHelpText>Program instructor must be entered as a contact.</inlineHelpText>
    <label>Instructor 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Programs (Instructor 1)</relationshipLabel>
    <relationshipName>Programs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/Program_Attendance__c.object-meta.xml
<CustomObject>
    <description>Contact who attends a specific Session of a Program. 
Junction object connecting Contact with Session.</description>
    <label>Program Attendance</label>
    <nameField>
        <displayFormat>Attendance-{0000}</displayFormat>
        <label>Attendance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <formula>Program__r.Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Referenced by Apex logic in TakeAttendance and ManageRegistrations. Auto-populated by Apex or Process Builder.</description>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/Program_Session__c.field-meta.xml
<CustomField>
    <fullName>Program_Session__c</fullName>
    <label>Program Session</label>
    <referenceTo>Program_Session__c</referenceTo>
    <relationshipLabel>Program Attendance</relationshipLabel>
    <relationshipName>Program_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Attendance__c/fields/ServiceDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceDate__c</fullName>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Registration__c/Program_Registration__c.object-meta.xml
<CustomObject>
    <description>Junction object connecting Programs with Contacts</description>
    <label>Program Registration</label>
    <nameField>
        <displayFormat>Registration-{0000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Person signed up for the program</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Registrations</relationshipLabel>
    <relationshipName>Program_Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Registration__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>Program which contact is signed up for</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Registrations</relationshipLabel>
    <relationshipName>Program_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Session__c/Program_Session__c.object-meta.xml
<CustomObject>
    <description>Junction object connecting Program with Attendee</description>
    <label>Program Session</label>
    <nameField>
        <displayFormat>Session-{0000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Session meeting date</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Session__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <description>From program.</description>
    <formula>Program__r.Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From program.</inlineHelpText>
    <label>Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Session__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Sessions </relationshipLabel>
    <relationshipName>Program_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LoadData.cls
public with sharing class LoadData {
    
    @AuraEnabled
    public static void loadContacts() {

        Account acc = new Account(Name='MASH 4077');
        insert acc;

        StaticResource defaultResource = [SELECT s.Body From StaticResource s WHERE s.Name LIKE 'MASHPeople%'];
        blob tempB = defaultResource.Body;
        String contentFile = tempB.toString();
        String[] filelines = contentFile.split('\n');
        List<Contact> contacts = new List<Contact>();
        for (Integer i=1;i<filelines.size();i++)
            {
            Contact temp = new Contact();
            String[] inputvalues = filelines[i].split(',');
            temp.FirstName = inputValues[0];
            temp.LastName = inputValues[1];
            temp.Birthdate = date.parse(inputValues[2]);
            temp.MailingPostalCode = inputValues[3];
            temp.Phone = inputValues[4];
            temp.Email = inputvalues[5];
            temp.Barcode__c = inputvalues[6];
            temp.AccountId = acc.Id;
            contacts.add(temp);
        }
        System.debug(contacts.size());
        insert contacts; 

    }

    @AuraEnabled
    public static void loadPrograms() {

        List<Program_Registration__c> registrations = new List<Program_Registration__c>();

        Program__c prog1 = new Program__c();
        prog1.Active__c = true;
        prog1.Name = 'Dressmaking';
        prog1.Description__c = 'Learn to make dresses that will be the envy of your friends (or get you a Section 8!)';
        prog1.Instructor1__c = [SELECT Id FROM Contact WHERE LastName='Klinger'].Id;
        prog1.Days__c = 'Friday';
        prog1.Hours__c = 3;
        insert prog1;
        System.debug('prog1 ' + prog1 );

        Set<String> dressMakers = new Set<String>{'Houlihan', 'Cutler', 'Rayburn', 'Bigelow','Straminsky'};
        List<Contact> cons1 = [SELECT Id FROM Contact WHERE LastName IN :dressMakers];
        for(Contact c: cons1) {
            Program_Registration__c reg = new Program_Registration__c();
            reg.Contact__c = c.Id;
            reg.Program__c = prog1.Id;
            registrations.add(reg);
        }

        Program__c prog2 = new Program__c();
        prog2.Active__c = true;
        prog2.Name = 'Book Club';
        prog2.Description__c = 'Discover literary classics and enjoy fine wine.';
        prog2.Instructor1__c = [SELECT Id FROM Contact WHERE LastName='Winchester'].Id;
        prog2.Days__c = 'Thursday';
        prog2.Hours__c = 2;
        insert prog2;

        Set<String> bookWorms = new Set<String>{'Potter','Bayliss', 'Nakahara', 'Friedman', 'Mulchahey','Burns'};
        List<Contact> cons2 = [SELECT Id FROM Contact WHERE LastName IN :bookWorms];
        for(Contact c: cons2) {
            Program_Registration__c reg = new Program_Registration__c();
            reg.Contact__c = c.Id;
            reg.Program__c = prog2.Id;
            registrations.add(reg);
        }

        Program__c prog3 = new Program__c();
        prog3.Active__c = true;
        prog3.Name = 'Homebrewing';
        prog3.Description__c = 'Wine, beer and more!';
        prog3.Instructor1__c = [SELECT Id FROM Contact WHERE LastName='Pierce'].Id;
        prog3.Days__c = 'Saturday';
        prog3.Hours__c = 3;
        insert prog3;

        Set<String> boozers = new Set<String>{'Blake','Hunnicut','McIntyre','Bigelow','Friedman','Houlihan','Zale'};
        List<Contact> cons3 = [SELECT Id FROM Contact WHERE LastName IN :boozers];
        for(Contact c: cons3) {
            Program_Registration__c reg = new Program_Registration__c();
            reg.Contact__c = c.Id;
            reg.Program__c = prog3.Id;
            registrations.add(reg);
        }

        Program__c prog4 = new Program__c();
        prog4.Active__c = true;
        prog4.Name = 'Hygiene Lecture';
        prog4.Description__c = 'Demo for Manage Registrations component';
        prog4.Instructor1__c = [SELECT Id FROM Contact WHERE LastName='Blake'].Id;
        prog4.Days__c = 'Wednesday';
        prog3.Hours__c = 1;
        insert prog4;

        
        List<Contact> cons4 = [SELECT Id FROM Contact WHERE LastName != 'Blake'];
        for(Contact c: cons4) {
            Program_Registration__c reg = new Program_Registration__c();
            reg.Contact__c = c.Id;
            reg.Program__c = prog4.Id;
            registrations.add(reg);
        }

        insert registrations;
    }

    @AuraEnabled
    public static void loadProgramSessions() {

        Map<Integer, String> weekdayMap = new Map<Integer,String>();
        List<String> weekdays = new List<String>{'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'};
        for(Integer i = 1; i <= 7; i++) {
            weekdayMap.put(i, weekdays[i-1]);
        }
        Integer dayOfWeek = getWeekdayFromDate(date.today());
        List<Program_Session__c> sessions = new List<Program_Session__c>();
		List<Program__c> programs = getPrograms();
        for (Program__c program: programs) {
            String days = program.Days__c;
            Integer offset = 0;
            while(!days.contains(weekdayMap.get(dayOfWeek))) {
                offset++;
                dayOfWeek = getWeekdayFromDate(date.today().addDays(offset));
            }
            for(Integer i = 1; i <= 6; i++) {
                Program_Session__c session = new Program_Session__c();
                session.Program__c = program.Id;
                if(program.Name == 'Hygiene Lecture') {
                    session.Date__c = date.today().addDays(-(i * 60) + offset);
                } else {
                    session.Date__c = date.today().addDays(-(i * 7) + offset);
                }
                System.debug(session);
                sessions.add(session);
            }   
        }
        insert sessions;
    }

    @AuraEnabled
    public static void loadSessionAttendance() {
        List<Program_Attendance__c> attendance = new List<Program_Attendance__c>();
        List<Program__c> programs = [SELECT Name, (SELECT Contact__c FROM Program_Registrations__r),
                                    (SELECT Date__c FROM Program_Sessions__r ORDER BY Date__c) FROM Program__c];
        for(Program__c program: programs) {
            List<Program_Registration__c> regs = program.Program_Registrations__r;
            List<Program_Session__c> sessions = program.Program_Sessions__r;
            if(program.Name != 'Hygiene Lecture') {  
                for(Program_Session__c session: sessions) {
                    //select one registrant to not attend
                    Integer randomNumber = Integer.valueof((Math.random() * regs.size()));
                    for(Integer i=0; i<regs.size(); i++) {
                        if(i != randomNumber) {
                            Program_Attendance__c att = new Program_Attendance__c();
                            att.Program__c = program.Id;
                            att.Program_Session__c = session.Id;
                            att.Contact__c = regs[i].Contact__c;
                            att.ServiceDate__c = session.Date__c;
                            attendance.add(att);
                        }// end if
                    }// end for loop
                }// end session loop
            } else { 
                // Hygiene Lecture!
                Integer s = 0;
                for(Program_Session__c session: sessions) {
                    if(s == 0) {
                        //everyone attends first session!
                        for(Program_Registration__c r: regs) {
                            Program_Attendance__c att = new Program_Attendance__c();
                            att.Program__c = program.Id;
                            att.Program_Session__c = session.Id;
                            att.Contact__c = r.Contact__c;
                            att.ServiceDate__c = session.Date__c;
                            attendance.add(att);
                        }
                    } else {
                        //only first 10 registrants attend each session
                        for(Integer i = 0; i < regs.size()/2; i++) {
                            Program_Attendance__c att = new Program_Attendance__c();
                            att.Program__c = program.Id;
                            att.Program_Session__c = session.Id;
                            att.Contact__c = regs[i].Contact__c;
                            att.ServiceDate__c = session.Date__c;
                            attendance.add(att);
                        }
                    } // end else   
                    s++;
                }// end session loop
            } // end else loop
        }// end program loop

        insert attendance;
    }
    
    public static List<Program__c> getPrograms() {
        return [SELECT Name, Days__c FROM Program__c];
    }
    
    public static Integer getWeekdayFromDate(Date myDate) {
        DateTime dt = DateTime.newInstance(myDate, Time.newInstance(0,0,0,0));
		String dayOfWeek = dt.format('u');
        return Integer.ValueOf(dayOfWeek);
    }

    
}